# Default values for test app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: hellorings.azurecr.io/hellobedrock.acme.frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  containerPort: 8080
